- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.3.3
  hooks:
    - id: go-fmt
    - id: go-lint
- repo: local
  hooks:
    - id: copyright_checker
      name: copyright_checker
      entry: python ./scripts/copyright.py
      language: system
      files: \.(go|py|sh)$
